server:
  port: 8080

spring:
  application:
    name: ops-backend
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
